### ISSUE TITLE
SIGABRT on startup

### ISSUE THREAD

**Issue by SirCmpwn** [Alexays/Waybar#10]
```
(gdb) bt full
#0  0x00007f375814fb5f in raise () at /usr/lib/libc.so.6
#1  0x00007f375813a452 in abort () at /usr/lib/libc.so.6
#2  0x00007f375864d71c in pa_signal_init () at /usr/lib/libpulse.so.0
#3  0x0000558fb175a599 in waybar::modules::Pulseaudio::Pulseaudio(Json::Value) (this=0x558fb3178800, config=...) at ../src/modules/pulseaudio.cpp:13
#4  0x0000558fb175e5ae in waybar::Factory::makeModule(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) (this=0x7ffebbe5f710, name="pulseaudio")
    at ../src/factory.cpp:22
#5  0x0000558fb173e3bc in waybar::Bar::_setupWidgets() (this=0x558fb31da700) at ../src/bar.cpp:181
        module = @0x558fb3114600: {_vptr.IModule = 0x558fb1793ac8 <vtable for waybar::modules::Network+16>}
        name = 
          {static null = @0x7f375a95a040, static nullRef = @0x7f375a95a040, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 94075674253840, uint_ = 94075674253840, real_ = 4.6479558758174189e-310, bool_ = 16, string_ = 0x558fb3255a10 "\n", map_ = 0x558fb3255a10}, type_ = Json::stringValue, allocated_ = 1, comments_ = 0x0, start_ = 78, limit_ = 90}
        __for_range = 
          @0x558fb3282cc0: {static null = @0x7f375a95a040, static nullRef = @0x7f375a95a040, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 94075674379248, uint_ = 94075674379248, real_ = 4.6479558820133974e-310, bool_ = 240, string_ = 0x558fb32743f0 "\220\234\022\263\217U", map_ = 0x558fb32743f0}, type_ = Json::arrayValue, allocated_ = 0, comments_ = 0x0, start_ = 77, limit_ = 139}
        __for_begin = Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value>>.: 
{<Json::ValueIteratorBase> = {current_ = {_M_node = 0x558fb31f4510}, isNull_ = false}, <No data fields>}
        __for_end = Python Exception <class 'gdb.error'> No type named std::_Rb_tree_node<std::pair<Json::Value::CZString const, Json::Value>>.: 
{<Json::ValueIteratorBase> = {current_ = {_M_node = 0x558fb32743f8}, isNull_ = false}, <No data fields>}
        left = @0x558fb3286600: <incomplete type>
        center = @0x558fb3258d10: <incomplete type>
        right = @0x558fb3114760: <incomplete type>
        box1 = @0x558fb3206e30: <incomplete type>
        factory = 
            {_bar = @0x558fb31da700, _config = {static null = @0x7f375a95a040, static nullRef = @0x7f375a95a040, static minLargestInt = -9223372036854775808, static maxLargestInt = 9223372036854775807, static maxLargestUInt = 18446744073709551615, static minInt = -2147483648, static maxInt = 2147483647, static maxUInt = 4294967295, static minInt64 = -9223372036854775808, static maxInt64 = 9223372036854775807, static maxUInt64 = 18446744073709551615, value_ = {int_ = 94075675918272, uint_ = 94075675918272, real_ = 4.647955958051286e-310, bool_ = 192, string_ = 0x558fb33ebfc0 "0k-X7\177", map_ = 0x558fb33ebfc0}, type_ = Json::objectValue, allocated_ = 0, comments_ = 0x0, start_ = 0, limit_ = 588}}
#6  0x0000558fb173d2cf in waybar::Bar::Bar(waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> >&&) (this=0x558fb31da700, client=..., p_output=...)
    at ../src/bar.cpp:26
        positionBottom = false
        gdkWindow = 0x558fb175cf16 <std::vector<std::unique_ptr<waybar::Bar, std::default_delete<waybar::Bar> >, std::allocator<std::unique_ptr<waybar::Bar, std::default_delete<waybar::Bar> > > >::back()+76>
        outputListener = 
    {geometry = 0x558fb173d540 <waybar::Bar::_handleGeometry(void*, wl_output*, int, int, int, int, int, char const*, char const*, int)>, mode = 0x558fb173d55e <waybar::Bar::_handleMode(void*, wl_output*, unsigned int, int, int, int)>, done = 0x558fb173d598 <waybar::Bar::_handleDone(void*, wl_output*)>, scale = 0x558fb173d5a8 <waybar::Bar::_handleScale(void*, wl_output*, int)>}
        layerSurfaceListener = 
    {configure = 0x558fb173d5ba <waybar::Bar::_layerSurfaceHandleConfigure(void*, zwlr_layer_surface_v1*, unsigned int, unsigned int, unsigned int)>, closed = 0x558fb173d70e <waybar::Bar::_layerSurfaceHandleClosed(void*, zwlr_layer_surface_v1*)>}
#7  0x0000558fb175c626 in std::make_unique<waybar::Bar, waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> > >(waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> >&&) (__args#0=..., __args#1=...) at /usr/include/c++/8.2.0/bits/unique_ptr.h:831
#8  0x0000558fb175c346 in waybar::util::ptr_vec<waybar::Bar>::emplace_back<waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> > >(waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> >&&) (this=0x7ffebbe5fe38, args#0=..., args#1=...) at ../include/util/ptr_vec.hpp:174
#9  0x0000558fb175be02 in waybar::Client::_handle_global(void*, wl_registry*, unsigned int, char const*, unsigned int) (data=0x7ffebbe5fdb0, registry=0x558fb31ba2a0, name=23, interface=0x558fb31baa90 "wl_output", version=3) at ../src/client.cpp:52
        output = std::unique_ptr<wl_output *> = {get() = 0x0}
        o = 0x7ffebbe5fdb0
#10 0x00007f3757f131c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#11 0x00007f3757f12c2a in ffi_call () at /usr/lib/libffi.so.6
#12 0x00007f375ab6af9f in  () at /usr/lib/libwayland-client.so.0
#13 0x00007f375ab6770a in  () at /usr/lib/libwayland-client.so.0
#14 0x00007f375ab68c5c in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#15 0x00007f375ab690ac in wl_display_roundtrip_queue () at /usr/lib/libwayland-client.so.0
#16 0x0000558fb175bf34 in waybar::Client::bind_interfaces() (this=0x7ffebbe5fdb0) at ../src/client.cpp:76
        registry_listener = 
    {global = 0x558fb175bd0e <waybar::Client::_handle_global(void*, wl_registry*, unsigned int, char const*, unsigned int)>, global_remove = 0x558fb175bed0 <waybar::Client::_handle_global_remove(void*, wl_registry*, unsigned int)>}
#17 0x0000558fb175bf57 in waybar::Client::main(int, char**) (this=0x7ffebbe5fdb0, argc=1, argv=0x7ffebbe5ff58) at ../src/client.cpp:81
#18 0x0000558fb173c13f in main(int, char**) (argc=1, argv=0x7ffebbe5ff58) at ../src/main.cpp:22
        c = 
                {height = 30, cssFile = "./resources/style.css", configFile = "./resources/config", gtk_main = <incomplete type>, gdk_display = {pCppObject_ = 0x558fb3198440}, wlDisplay = 0x558fb30d2090, registry = 0x558fb31ba2a0, layer_shell = 0x558fb31ff430, idle_manager = 0x558fb31ff540, seat = 0x558fb31ff320, bars = {_order = std::vector of length 1, capacity 1 = {std::unique_ptr<waybar::Bar> = {get() = 0x558fb30f2710}}}}

```

**Comment by Alexays** [comment]
Thanks for testing :laughing: 
I noticed I didn't need that call. Maybe it fixes your crash.
