### ISSUE TITLE
Crash when unplugging HDMI monitor

### ISSUE THREAD

**Issue by jayache80** [Alexays/Waybar#1202]
I have a single HDMI monitor for my computer which runs sway and waybar. Sometimes I unplug my monitor, and then plug it back in. Waybar always crashes the moment I unplug my HDMI cable from my monitor. Here's the coredump:

```
(gdb) thread apply all bt

Thread 12 (Thread 0x7f4c3a3f0600 (LWP 134148)):
#0  0x00007f4c3ba658ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007f4c3ba5a743 in __pthread_clockjoin_ex () at /usr/lib/libpthread.so.0
#2  0x00007f4c3bca5628 in __gthread_join (__value_ptr=0x0, __threadid=<optimized out>) at /build/gcc/src/gcc-build/x86_64-pc-linux-gnu/libstdc++-v3/include/x86_64-pc-linux-gnu/bits/gthr-default.h:669
#3  std::thread::join() (this=0x5648891f7150) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:112
#4  0x0000564888d46885 in  ()
#5  0x0000564888cea58f in  ()
#6  0x0000564888cea800 in  ()
#7  0x0000564888cef017 in  ()
#8  0x00007f4c3c1105d9 in  () at /usr/lib/libglibmm-2.4.so.1
#9  0x00007f4c3bf83015 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#10 0x00007f4c3bfd6b99 in  () at /usr/lib/libglib-2.0.so.0
#11 0x00007f4c3bf80871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#12 0x00007f4c3c2128b6 in g_application_run () at /usr/lib/libgio-2.0.so.0
#13 0x0000564888cc2f8f in  ()
#14 0x0000564888cc22f6 in main ()

Thread 11 (Thread 0x7f4c17fff640 (LWP 134171)):
#0  0x00007f4c3b977b2f in poll () at /usr/lib/libc.so.6
#1  0x00007f4c3becbae4 in  () at /usr/lib/libpulse.so.0
#2  0x00007f4c3beb54b9 in pa_mainloop_poll () at /usr/lib/libpulse.so.0
#3  0x00007f4c3bebf709 in pa_mainloop_iterate () at /usr/lib/libpulse.so.0
#4  0x00007f4c3bebf7c1 in pa_mainloop_run () at /usr/lib/libpulse.so.0
#5  0x00007f4c3becfc9e in  () at /usr/lib/libpulse.so.0
#6  0x00007f4c3aebc403 in  () at /usr/lib/pulseaudio/libpulsecommon-15.0.so
#7  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#8  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 10 (Thread 0x7f4c39901640 (LWP 134152)):
#0  0x00007f4c3b977b2f in poll () at /usr/lib/libc.so.6
#1  0x00007f4c3bfd6b29 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f4c3bf80871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f4c3bf808c2 in  () at /usr/lib/libglib-2.0.so.0
#4  0x00007f4c3bfb12c1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 9 (Thread 0x7f4c2ae9c640 (LWP 134164)):
#0  0x00007f4c3ba62a2c in recv () at /usr/lib/libpthread.so.0
#1  0x0000564888d04a8c in  ()
#2  0x0000564888d0508a in  ()
#3  0x0000564888d055d5 in  ()
#4  0x0000564888cd9561 in  ()
#5  0x00007f4c3bca53c4 in std::execute_native_thread_routine(void*) (__p=0x5648893ccf10) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#6  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#7  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 8 (Thread 0x7f4c28e98640 (LWP 134169)):
--Type <RET> for more, q to quit, c to continue without paging--c
#0  0x00007f4c3b98292e in epoll_wait () at /usr/lib/libc.so.6
#1  0x0000564888d19ddb in  ()
#2  0x0000564888cd9561 in  ()
#3  0x00007f4c3bca53c4 in std::execute_native_thread_routine(void*) (__p=0x5648893b5d70) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#4  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#5  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 7 (Thread 0x7f4c29e9a640 (LWP 134167)):
#0  0x00007f4c3ba658ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007f4c3ba5f842 in pthread_cond_clockwait () at /usr/lib/libpthread.so.0
#2  0x0000564888cfe3f6 in  ()
#3  0x0000564888cd9561 in  ()
#4  0x00007f4c3bca53c4 in std::execute_native_thread_routine(void*) (__p=0x5648893c15b0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#5  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 6 (Thread 0x7f4c2b69d640 (LWP 134163)):
#0  0x00007f4c3ba62a2c in recv () at /usr/lib/libpthread.so.0
#1  0x0000564888d04a8c in  ()
#2  0x0000564888d04e7c in  ()
#3  0x0000564888d04fbf in  ()
#4  0x0000564888d0b52c in  ()
#5  0x0000564888d05195 in  ()
#6  0x0000564888d05096 in  ()
#7  0x0000564888d0bf15 in  ()
#8  0x0000564888cd9561 in  ()
#9  0x00007f4c3bca53c4 in std::execute_native_thread_routine(void*) (__p=0x5648891d3ab0) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#10 0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#11 0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 5 (Thread 0x7f4c388f0640 (LWP 134154)):
#0  0x00007f4c3b977b2f in poll () at /usr/lib/libc.so.6
#1  0x00007f4c3bfd6b29 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f4c3bf80871 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#3  0x00007f4c388f6ebe in  () at /usr/lib/gio/modules/libdconfsettings.so
#4  0x00007f4c3bfb12c1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 4 (Thread 0x7f4c3a3e9640 (LWP 134151)):
#0  0x00007f4c3b8c1ae2 in sigtimedwait () at /usr/lib/libc.so.6
#1  0x00007f4c3ba633ac in sigwait () at /usr/lib/libpthread.so.0
#2  0x0000564888ce042c in  ()
#3  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#4  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 3 (Thread 0x7f4c2bfff640 (LWP 134155)):
#0  0x00007f4c3b977b2f in poll () at /usr/lib/libc.so.6
#1  0x00007f4c3bfd6b29 in  () at /usr/lib/libglib-2.0.so.0
#2  0x00007f4c3bf82693 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#3  0x00007f4c3c2478c8 in  () at /usr/lib/libgio-2.0.so.0
#4  0x00007f4c3bfb12c1 in  () at /usr/lib/libglib-2.0.so.0
#5  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 2 (Thread 0x7f4c29699640 (LWP 134168)):
#0  0x00007f4c3ba658ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#1  0x00007f4c3ba5f842 in pthread_cond_clockwait () at /usr/lib/libpthread.so.0
#2  0x0000564888d1b119 in  ()
#3  0x0000564888cd9561 in  ()
#4  0x00007f4c3bca53c4 in std::execute_native_thread_routine(void*) (__p=0x5648893afa50) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#5  0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#6  0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6

Thread 1 (Thread 0x7f4c177fe640 (LWP 134173) (Exiting)):
#0  0x00007f4c3b8c0d22 in raise () at /usr/lib/libc.so.6
#1  0x00007f4c3b8aa862 in abort () at /usr/lib/libc.so.6
#2  0x00007f4c3bc6b802 in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f4c3bc77c8a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007f4c3bc77cf7 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007f4c3bc775fd in __cxxabiv1::__gxx_personality_v0(int, _Unwind_Action, _Unwind_Exception_Class, _Unwind_Exception*, _Unwind_Context*) (version=<optimized out>, actions=10, exception_class=0, ue_header=0x7f4c177fecb0, context=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_personality.cc:673
#6  0x00007f4c3ba820b4 in _Unwind_ForcedUnwind_Phase2 (exc=0x7f4c177fecb0, context=0x7f4c177fd350, frames_p=0x7f4c177fd258) at /build/gcc/src/gcc/libgcc/unwind.inc:182
#7  0x00007f4c3ba827b2 in _Unwind_ForcedUnwind (exc=0x7f4c177fecb0, stop=<optimized out>, stop_argument=0x7f4c177fdc30) at /build/gcc/src/gcc/libgcc/unwind.inc:217
#8  0x00007f4c3ba62374 in __pthread_unwind () at /usr/lib/libpthread.so.0
#9  0x00007f4c3ba57c09 in  () at /usr/lib/libpthread.so.0
#10 0x00007f4c3ba63870 in <signal handler called> () at /usr/lib/libpthread.so.0
#11 0x00007f4c3ba658ca in __futex_abstimed_wait_common64 () at /usr/lib/libpthread.so.0
#12 0x00007f4c3ba5f574 in pthread_cond_timedwait@@GLIBC_2.3.2 () at /usr/lib/libpthread.so.0
#13 0x0000564888d3e5a6 in  ()
#14 0x0000564888cd9561 in  ()
#15 0x00007f4c3bca53c4 in std::execute_native_thread_routine(void*) (__p=0x564889299360) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:82
#16 0x00007f4c3ba59259 in start_thread () at /usr/lib/libpthread.so.0
#17 0x00007f4c3b9825e3 in clone () at /usr/lib/libc.so.6
```

**Comment by equalis3r** [comment]
I think your issue is the same as #1158 You may want to install the git version.

**Comment by jayache80** [comment]
> I think your issue is the same as #1158
D'oh!

> You may want to install the git version.
The problem seems to have gone away with waybar-git r1574.9aec6bb-1

Sorry for the noise
