### ISSUE TITLE
Sigsegv crash

### ISSUE THREAD

**Issue by gmykhailiuta** [Alexays/Waybar#1307]
Trying to run waybar built from latest master (b511103), but it crashes with SIGSEGV. Older package from official Arch repos works fine.

I'm sure that it must be something related to my local setup since I haven't found similar issue reported. But I already tried all kinds of combinations of the versions of libs mentioned in stacktrace with no luck. Am I missing something? Would highly appreciate any hint.

GDB output and stacktrace are below (used default config file).

```
Starting program: /usr/bin/waybar
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2b38640 (LWP 2022896)]
[New Thread 0x7ffff201f640 (LWP 2022897)]
[New Thread 0x7ffff17fe640 (LWP 2022898)]
[New Thread 0x7ffff0f5a640 (LWP 2022899)]
[New Thread 0x7fffe3fff640 (LWP 2022900)]
[2021-11-04 15:52:04.671] [info] Using configuration file /etc/xdg/waybar/config
[2021-11-04 15:52:04.672] [info] Using CSS file /etc/xdg/waybar/style.css
[New Thread 0x7fffe37fe640 (LWP 2022901)]
[New Thread 0x7fffe2ffd640 (LWP 2022902)]
[Detaching after fork from child process 2022903]
[New Thread 0x7fffe27fc640 (LWP 2022904)]
[2021-11-04 15:52:04.690] [error] media stopped unexpectedly, is it endless?
[Thread 0x7fffe27fc640 (LWP 2022904) exited]
[New Thread 0x7fffe1ffb640 (LWP 2022905)]
[New Thread 0x7fffe17fa640 (LWP 2022906)]
[New Thread 0x7fffe0ff9640 (LWP 2022907)]
[2021-11-04 15:52:04.694] [warning] Waybar has been built without rfkill support.
[New Thread 0x7fffd3fff640 (LWP 2022908)]
[New Thread 0x7fffd37fe640 (LWP 2022909)]
[New Thread 0x7fffd2ffd640 (LWP 2022910)]
[New Thread 0x7fffd27fc640 (LWP 2022911)]
[New Thread 0x7fffd1ffb640 (LWP 2022912)]
[2021-11-04 15:52:04.697] [info] Found device XIUDI XD60rev3 Keyboard at '/dev/input/event23'
[New Thread 0x7fffd17fa640 (LWP 2022913)]

Thread 1 "waybar" received signal SIGSEGV, Segmentation fault.
0x00007ffff6632c63 in __memcmp_avx2_movbe () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff6632c63 in __memcmp_avx2_movbe () at /usr/lib/libc.so.6
#1  0x00005555555cd379 in  ()
#2  0x00005555555cec09 in  ()
#3  0x00005555555c98b5 in  ()
#4  0x00005555555c923f in  ()
#5  0x00005555555ce68d in  ()
#6  0x0000555555580bee in  ()
#7  0x000055555559f755 in  ()
#8  0x000055555559f9fb in  ()
#9  0x00005555555a053d in  ()
#10 0x00005555555a7f3e in  ()
#11 0x00007ffff64d10dd in  () at /usr/lib/libffi.so.7
#12 0x00007ffff64cf9e1 in  () at /usr/lib/libffi.so.7
#13 0x00007ffff7f8e143 in  () at /usr/lib/libwayland-client.so.0
#14 0x00007ffff7f8a583 in  () at /usr/lib/libwayland-client.so.0
#15 0x00007ffff7f8bcfc in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#16 0x00007ffff700eab5 in  () at /usr/lib/libgdk-3.so.0
#17 0x00007ffff6fdee2b in gdk_display_get_event () at /usr/lib/libgdk-3.so.0
#18 0x00007ffff7017c04 in  () at /usr/lib/libgdk-3.so.0
#19 0x00007ffff6c014dc in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff6c55799 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff6bfebc1 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff6ec52fe in g_application_run () at /usr/lib/libgio-2.0.so.0
#23 0x000055555557f175 in  ()
#24 0x000055555557e4d6 in main ()
```

Dependencies versions:
- libffi 3.3-2
- wayland-git 1.19.0.r16.g8f1795f-1
- gtk3 1:3.24.30+90+g20be04f7ac-1
- glib2 2.70.1-1

**Comment by gmykhailiuta** [comment]
Adding valgrind output: https://gist.github.com/gmykhailiuta/0d62ea2130a631f64372955ec4d915e5

**Comment by AzP** [comment]
I had a similar crash on 0.9.9 and building master fixed it for me.

**Comment by Alexays** [comment]
Fixed with latest version
