### ISSUE TITLE
Waybar randomly disappears

### ISSUE THREAD

**Issue by jahway603** [Alexays/Waybar#1344]
I am not able to determine what is causing the issue (the root cause) but when I'm not active at my desktop for a while and then I come back to it, the waybar has disappeared and I have to use my Sway key sequence to "refresh" and bring it back.

OS: Arch with SwayWM
Version: waybar-git (which pulls from this repo)

**Comment by luispabon** [comment]
It's got to do with displays activating and deactivating. It's a relatively new issue, I recently upgraded Waybar to latest master.

Coredump bt full:

```
coredumpctl gdb                                                                                                                                                                   Tue 07 Dec 2021 11:21:49 GMT
           PID: 3818979 (waybar)
           UID: 1000 (luis)
           GID: 1000 (luis)
        Signal: 11 (SEGV)
     Timestamp: Tue 2021-12-07 11:20:45 GMT (1min 7s ago)
  Command Line: waybar
    Executable: /usr/local/bin/waybar
 Control Group: /user.slice/user-1000.slice/session-1306.scope
          Unit: session-1306.scope
         Slice: user-1000.slice
       Session: 1306
     Owner UID: 1000 (luis)
       Boot ID: 91fadf7eef374b798661ec6c76a4e1a2
    Machine ID: 9fe5413e488441b384b693754a23e855
      Hostname: luis-XPS-15-9560
       Storage: /var/lib/systemd/coredump/core.waybar.1000.91fadf7eef374b798661ec6c76a4e1a2.3818979.1638876045000000.zst (present)
     Disk Size: 2.7M
       Message: Process 3818979 (waybar) of user 1000 dumped core.
                
                Stack trace of thread 3818979:
                #0  0x00000000000000b1 n/a (n/a + 0x0)

GNU gdb (Ubuntu 11.1-0ubuntu2) 11.1
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/local/bin/waybar...
(No debugging symbols found in /usr/local/bin/waybar)

warning: Can't open file /memfd:pulseaudio (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:gdk-wayland (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:wayland-cursor (deleted) during file-backed mapping note processing

warning: Can't open file /home/luis/.config/dconf/user (deleted) during file-backed mapping note processing

warning: Can't open file /run/user/1000/dconf/user (deleted) during file-backed mapping note processing
[New LWP 3818979]
[New LWP 3818981]
[New LWP 3818999]
[New LWP 3818980]
[New LWP 3835125]
[New LWP 3818984]
[New LWP 3818992]
[New LWP 3835126]
[New LWP 3835138]
[New LWP 3835127]
[New LWP 3818985]
[New LWP 3818997]
[New LWP 3818989]
[New LWP 3835130]
[New LWP 3818986]
[New LWP 3818983]
[New LWP 3835123]
[New LWP 3819000]
[New LWP 3818993]
[New LWP 3835124]
[New LWP 3818987]
[New LWP 3835139]
[New LWP 3818994]
[New LWP 3818995]
[New LWP 3818988]
[New LWP 3818998]
[New LWP 3835132]
[New LWP 3835133]
[New LWP 3835134]
[New LWP 3835136]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `waybar'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000000000b1 in ?? ()
[Current thread is 1 (Thread 0x7f097afeff80 (LWP 3818979))]
(gdb) bt full
#0  0x00000000000000b1 in  ()
#1  0x0000556e407a4b97 in waybar::Bar::~Bar() ()
#2  0x0000556e407b0813 in waybar::Client::handleDeferredMonitorRemoval(Glib::RefPtr<Gdk::Monitor>) ()
#3  0x0000556e407b1ce7 in sigc::internal::slot_call0<sigc::bind_functor<-1, sigc::bound_mem_functor1<void, waybar::Client, Glib::RefPtr<Gdk::Monitor> >, Glib::RefPtr<Gdk::Monitor>, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>, void>::call_it(sigc::internal::slot_rep*) ()
#4  0x00007f097ec13cd9 in  () at /lib/x86_64-linux-gnu/libglibmm-2.4.so.1
#5  0x00007f097ea567c4 in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007f097eaa9f08 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007f097ea54003 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007f097ed23c1d in g_application_run () at /lib/x86_64-linux-gnu/libgio-2.0.so.0
#9  0x0000556e4077bd72 in waybar::Client::main(int, char**) ()
#10 0x0000556e4077abb5 in main ()
```

**Comment by jfred9** [comment]
Please test if pull request #1338 solves your problem.

**Comment by luispabon** [comment]
I'm compiling it now, I'll report back. Thank you.

**Comment by luispabon** [comment]
@jfred9 so far so good, it's survived a number of display connections and reconnections and suspend/resume cycles

**Comment by Alexays** [comment]
Nice, will close the issue :)
