### ISSUE TITLE
Running lutris causes segfault

### ISSUE THREAD

**Issue by Polluktus** [Alexays/Waybar#1639]
OS: Gentoo
Waybar version: [7b115913dea63aa5fd7deb68f1be2911d023a48d](https://github.com/Alexays/Waybar/commit/7b115913dea63aa5fd7deb68f1be2911d023a48d)
wlroots version: [30bf8a4303bc5df3cb87b7e6555592dbf8d95cf1](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/30bf8a4303bc5df3cb87b7e6555592dbf8d95cf1)

Sometimes running lutris causes segfault, to get this bt i run it around 10 times. It started happening after enabling icon in sway/window module. Also sometimes waybar shows `GLib-CRITICAL **: g_hash_table_lookup: assertion 'hash_table != NULL' failed
`
```
Starting program: /usr/bin/waybar                                                                                                                                           
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff5649640 (LWP 4392)]
[New Thread 0x7ffff4978640 (LWP 4393)]
[New Thread 0x7fffeffff640 (LWP 4394)]
[New Thread 0x7fffef7fe640 (LWP 4395)]
[New Thread 0x7fffeeffd640 (LWP 4396)]
[New Thread 0x7fffee79a640 (LWP 4397)]
[New Thread 0x7fffedf99640 (LWP 4398)]
[New Thread 0x7fffed798640 (LWP 4399)]
[Detaching after fork from child process 4400]
[New Thread 0x7fffecf97640 (LWP 4401)]
[Detaching after fork from child process 4402]
[New Thread 0x7fffd7fff640 (LWP 4403)]
[New Thread 0x7fffd77fe640 (LWP 4404)]
[New Thread 0x7fffd6ffd640 (LWP 4405)]
[New Thread 0x7fffd67fc640 (LWP 4406)]
[Detaching after fork from child process 4409]
[New Thread 0x7fffd5ffb640 (LWP 4410)]
[New Thread 0x7fffd57fa640 (LWP 4412)]
[Thread 0x7fffd57fa640 (LWP 4412) exited]
[New Thread 0x7fffd57fa640 (LWP 4419)]
[New Thread 0x7fffd4ff9640 (LWP 4420)]
[Thread 0x7fffd57fa640 (LWP 4419) exited]
[Thread 0x7fffd4ff9640 (LWP 4420) exited]
[New Thread 0x7fffd4ff9640 (LWP 4421)]
[New Thread 0x7fffd57fa640 (LWP 4422)]
[New Thread 0x7fffc7fff640 (LWP 4423)]
[Detaching after fork from child process 4424]
[New Thread 0x7fffc77fe640 (LWP 4425)]
[Detaching after fork from child process 4426]
[New Thread 0x7fffc6ffd640 (LWP 4427)]
[New Thread 0x7fffc67fc640 (LWP 4430)]
[New Thread 0x7fffc5ffb640 (LWP 4431)]
[New Thread 0x7fffc57fa640 (LWP 4432)]
[Detaching after fork from child process 4433]
[New Thread 0x7fffc4ff9640 (LWP 4434)]
[New Thread 0x7fffbffff640 (LWP 4446)]
[New Thread 0x7fffbf7fe640 (LWP 4447)]
[Thread 0x7fffbffff640 (LWP 4446) exited]
[Thread 0x7fffbf7fe640 (LWP 4447) exited]
[New Thread 0x7fffbf7fe640 (LWP 4448)]
[New Thread 0x7fffbffff640 (LWP 4449)]
[Thread 0x7fffbf7fe640 (LWP 4448) exited]
[Thread 0x7fffbffff640 (LWP 4449) exited]
[Detaching after fork from child process 4459]
[Detaching after fork from child process 4470]
[Detaching after fork from child process 4560]
[Detaching after fork from child process 4565]
[Detaching after fork from child process 4653]
[Detaching after fork from child process 4658]
[Thread 0x7fffeffff640 (LWP 4394) exited]
[Detaching after fork from child process 4679]
[Detaching after fork from child process 4680]
[Detaching after fork from child process 4707]
[Detaching after fork from child process 4708]
[Detaching after fork from child process 4861]
[Detaching after fork from child process 4862]
[Detaching after fork from child process 4904]
[Detaching after fork from child process 4905]

Thread 20 "waybar" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd57fa640 (LWP 4422)]
0x0000000000000000 in ?? ()
#0  0x0000000000000000 in  ()
#1  0x00007ffff6b10f28 in g_hash_table_lookup () at /usr/lib64/libglib-2.0.so.0
#2  0x00007ffff720db31 in gtk_icon_theme_has_icon () at /usr/lib64/libgtk-3.so.0
#3  0x00007ffff7d05920 in Gtk::IconTheme::has_icon(Glib::ustring const&) const () at /usr/lib64/libgtkmm-3.0.so.1
#4  0x00005555555c0c84 in waybar::modules::sway::Window::onCmd(waybar::modules::sway::Ipc::ipc_response const&) ()
#5  0x00005555555b4ce6 in sigc::internal::signal_emit1<void, bool, sigc::nil>::emit(sigc::internal::signal_impl*, bool const&) ()
#6  0x00005555555b9018 in waybar::modules::sway::Ipc::sendCmd(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#7  0x00005555555bee90 in waybar::modules::sway::Window::getTree() ()
#8  0x00005555555b4ce6 in sigc::internal::signal_emit1<void, bool, sigc::nil>::emit(sigc::internal::signal_impl*, bool const&) ()
#9  0x00005555555b9156 in waybar::modules::sway::Ipc::handleEvent() ()
#10 0x00005555555bdbc4 in std::_Function_handler<void (), waybar::modules::sway::Window::Window(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char
> > const&, waybar::Bar const&, Json::Value const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#11 0x0000555555592d51 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<waybar::util::SleeperThread::operator=(std::function<void ()>)::{lambda()#1}> > >::_M_ru
n() ()
#12 0x00007ffff6932290 in  () at /usr/lib/gcc/x86_64-pc-linux-gnu/11.3.0/libstdc++.so.6
#13 0x00007ffff65f9267 in  () at /lib64/libc.so.6
#14 0x00007ffff667bd4c in  () at /lib64/libc.so.6
```

**Comment by Alexays** [comment]
Did you still have the error?
