### ISSUE TITLE
waybar sigsegv

### ISSUE THREAD

**Issue by enedil** [Alexays/Waybar#1963]
I have no idea how exactly did it happend. Here's backtrace:
```
gef➤  bt full
#0  0x00007f781f5584ba in g_slist_remove () at /lib64/libglib-2.0.so.0
#1  0x0000563c898b30f0 in waybar::modules::SNI::Watcher::nameVanished(_GDBusConnection*, char const*, void*) (connection=<optimized out>, name=<optimized out>, data=0x563c8ace6d40) at ../src/modules/sni/watcher.cpp:160
        tmp = <optimized out>
        watch = 0x563c8ace6d40
#2  0x00007f781f7306c0 in do_call.lto_priv () at /lib64/libgio-2.0.so.0
#3  0x00007f781f730817 in on_name_owner_changed.lto_priv () at /lib64/libgio-2.0.so.0
#4  0x00007f781f7290ef in emit_signal_instance_in_idle_cb () at /lib64/libgio-2.0.so.0
#5  0x00007f781f537cb2 in g_idle_dispatch () at /lib64/libglib-2.0.so.0
#6  0x00007f781f538cbf in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#7  0x00007f781f58e598 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#8  0x00007f781f535f40 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#9  0x00007f781f70394d in g_application_run () at /lib64/libgio-2.0.so.0
#10 0x0000563c898367ea in waybar::Client::main(int, char**) (this=0x563c8abf7800, argc=<optimized out>, argv=<optimized out>) at /usr/include/glibmm-2.4/glibmm/refptr.h:259
        show_help = 0x0
        show_version = 0x0
        config_opt = ""
        style_opt = ""
        log_level = ""
        cli = warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<clara::detail::BoundFlagLambda<clara::detail::Help::Help(bool&)::{lambda(bool)#1}>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_ptr_inplace<clara::detail::BoundFlagLambda<clara::detail::Help::Help(bool&)::{lambda(bool)#1}>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
{
          <clara::detail::ParserBase> = {
            _vptr.ParserBase = 0x563c8992efd8 <vtable for clara::detail::Parser+16>
          }, 
          members of clara::detail::Parser:
          m_exeName = {
            <clara::detail::ComposableParserImpl<clara::detail::ExeName>> = {
              <clara::detail::ParserBase> = {
                _vptr.ParserBase = 0x563c8992efa0 <vtable for clara::detail::ExeName+16>
              }, <No data fields>}, 
            members of clara::detail::ExeName:
            m_name = std::shared_ptr<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> (use count 1, weak count 0) = {
              get() = 0x563c8ac189d0
            },
            m_ref = std::shared_ptr<clara::detail::BoundValueRefBase> (empty) = {
              get() = 0x0
            }
          },
          m_options = std::vector of length 6, capacity 6 = {{
              <clara::detail::ParserRefImpl<clara::detail::Opt>> = {
                <clara::detail::ComposableParserImpl<clara::detail::Opt>> = {
                  <clara::detail::ParserBase> = {
                    _vptr.ParserBase = 0x563c8992eac8 <vtable for clara::detail::Opt+16>
                  }, <No data fields>}, 
                members of clara::detail::ParserRefImpl<clara::detail::Opt>:
                m_optionality = clara::detail::Optionality::Optional,
                m_ref = std::shared_ptr<clara::detail::BoundRef> (use count 1, weak count 0) = {
                  get() = 0x563c8ac19880
                },
                m_hint = "",
                m_description = "display usage information"
              }, 
              members of clara::detail::Opt:
              m_optNames = std::vector of length 3, capacity 3 = {"-?", "-h", "--help"}
            }, {
              <clara::detail::ParserRefImpl<clara::detail::Opt>> = {
                <clara::detail::ComposableParserImpl<clara::detail::Opt>> = {
                  <clara::detail::ParserBase> = {
                    _vptr.ParserBase = 0x563c8992eac8 <vtable for clara::detail::Opt+16>
                  }, <No data fields>}, 
                members of clara::detail::ParserRefImpl<clara::detail::Opt>:
                m_optionality = clara::detail::Optionality::Optional,
                m_ref = std::shared_ptr<clara::detail::BoundRef> (use count 1, weak count 0) = {
                  get() = 0x563c8ac19800
                },
                m_hint = "",
                m_description = "Show version"
              }, 
              members of clara::detail::Opt:
              m_optNames = std::vector of length 2, capacity 2 = {"-v", "--version"}
            }, {
              <clara::detail::ParserRefImpl<clara::detail::Opt>> = {
                <clara::detail::ComposableParserImpl<clara::detail::Opt>> = {
                  <clara::detail::ParserBase> = {
                    _vptr.ParserBase = 0x563c8992eac8 <vtable for clara::detail::Opt+16>
                  }, <No data fields>}, 
                members of clara::detail::ParserRefImpl<clara::detail::Opt>:
                m_optionality = clara::detail::Optionality::Optional,
                m_ref = std::shared_ptr<clara::detail::BoundRef> (use count 1, weak count 0) = {
                  get() = 0x563c8ac19780
                },
                m_hint = "config",
                m_description = "Config path"
              }, 
              members of clara::detail::Opt:
              m_optNames = std::vector of length 2, capacity 2 = {"-c", "--config"}
            }, {
              <clara::detail::ParserRefImpl<clara::detail::Opt>> = {
                <clara::detail::ComposableParserImpl<clara::detail::Opt>> = {
                  <clara::detail::ParserBase> = {
                    _vptr.ParserBase = 0x563c8992eac8 <vtable for clara::detail::Opt+16>
                  }, <No data fields>}, 
                members of clara::detail::ParserRefImpl<clara::detail::Opt>:
                m_optionality = clara::detail::Optionality::Optional,
                m_ref = std::shared_ptr<clara::detail::BoundRef> (use count 1, weak count 0) = {
                  get() = 0x563c8ac19700
                },
                m_hint = "style",
                m_description = "Style path"
              }, 
              members of clara::detail::Opt:
              m_optNames = std::vector of length 2, capacity 2 = {"-s", "--style"}
            }, {
              <clara::detail::ParserRefImpl<clara::detail::Opt>> = {
                <clara::detail::ComposableParserImpl<clara::detail::Opt>> = {
                  <clara::detail::ParserBase> = {
                    _vptr.ParserBase = 0x563c8992eac8 <vtable for clara::detail::Opt+16>
                  }, <No data fields>}, 
                members of clara::detail::ParserRefImpl<clara::detail::Opt>:
                m_optionality = clara::detail::Optionality::Optional,
                m_ref = std::shared_ptr<clara::detail::BoundRef> (use count 1, weak count 0) = {
                  get() = 0x563c8ac19680
                },
                m_hint = "trace|debug|info|warning|error|critical|off",
                m_description = "Log level"
              }, 
              members of clara::detail::Opt:
              m_optNames = std::vector of length 2, capacity 2 = {"-l", "--log-level"}
            }, {
              <clara::detail::ParserRefImpl<clara::detail::Opt>> = {
                <clara::detail::ComposableParserImpl<clara::detail::Opt>> = {
                  <clara::detail::ParserBase> = {
                    _vptr.ParserBase = 0x563c8992eac8 <vtable for clara::detail::Opt+16>
                  }, <No data fields>}, 
                members of clara::detail::ParserRefImpl<clara::detail::Opt>:
                m_optionality = clara::detail::Optionality::Optional,
                m_ref = std::shared_ptr<clara::detail::BoundRef> (use count 1, weak count 0) = {
                  get() = 0x563c8ac19650
                },
                m_hint = "id",
                m_description = "Bar id"
              }, 
              members of clara::detail::Opt:
              m_optNames = std::vector of length 2, capacity 2 = {"-b", "--bar"}
            }},
          m_args = std::vector of length 0, capacity 0
        }
        res = {
          <clara::detail::ResultValueBase<clara::detail::ParseState>> = {
            <clara::detail::ResultBase> = {
              _vptr.ResultBase = 0x563c8992eb00 <vtable for clara::detail::BasicResult<clara::detail::ParseState>+16>,
              m_type = clara::detail::ResultBase::Ok
            }, 
            members of clara::detail::ResultValueBase<clara::detail::ParseState>:
            {
              m_value = {
                m_type = clara::detail::ParseResultType::Matched,
                m_remainingTokens = {
                  it = "M\213>A\366\207\344\000\000\000\001u<\362\017\020\004$H\215t$ L\211\352L\211\377\362\017\020L$\b\350\030\376\377\377H\211\351L\211\342H\211\336\362\017\020L$\030\362\017\020D$ L\211\377\350[\377\377\377\205\300uWM\213v\bM\205\366u",
                  itEnd = "M\213>A\366\207\344\000\000\000\001u<\362\017\020\004$H\215t$ L\211\352L\211\377\362\017\020L$\b\350\030\376\377\377H\211\351L\211\342H\211\336\362\017\020L$\030\362\017\020D$ L\211\377\350[\377\377\377\205\300uWM\213v\bM\205\366u",
                  m_tokenBuffer = std::vector of length 0, capacity 0
                }
              }
            }
          }, 
          members of clara::detail::BasicResult<clara::detail::ParseState>:
          m_errorMessage = ""
        }
        css_file = "/etc/xdg/waybar/style.css"
#11 0x0000563c8983539d in main(int, char**) (argc=0x3, argv=0x7ffd9273d708) at ../src/main.cpp:100
        client = 0x563c8abf7800
        ret = <optimized out>
```

Anything else I could provide?

**Comment by enedil** [comment]
yeah, memory corruption:
```
gef➤  ptype list
type = struct _GSList {
    gpointer data;
    GSList *next;
} *
gef➤  p list->next 
$11 = 0x2e706f746b736564 = {Cannot access memory at address 0x2e706f746b736564
```
0x2e706f746b736564 is not a valid pointer (exceeds 48 bits)

**Comment by enedil** [comment]
```
gef➤  fr 2
#2  0x0000563c898b30f0 in waybar::modules::SNI::Watcher::nameVanished (connection=<optimized out>, name=<optimized out>, data=0x563c8ace6d40) at ../src/modules/sni/watcher.cpp:160
160	    watch->watcher->items_ = g_slist_remove(watch->watcher->items_, watch);
gef➤  p *watch->watcher 
$24 = {
  bus_name_id_ = 0x8b02f3f0,
  hosts_ = 0x563c8af6cf40 = {0x656572662e67726f, <error reading variable: Cannot access memory at address 0x2e706f746b736564>
```
