### ISSUE TITLE
SIGSEGV when interfacing with xdg

### ISSUE THREAD

**Issue by tarberd** [Alexays/Waybar#20]
## What:
When trying to run waybar it halts to a segmentation fault, this is gdb's output:
```
(gdb) bt full
#0  0x00007ffff7d52ee4 in wl_proxy_marshal_constructor () at /usr/lib/libwayland-client.so.0
#1  0x000055555559166d in zxdg_output_manager_v1_get_xdg_output(zxdg_output_manager_v1*, wl_output*) (zxdg_output_manager_v1=0x8, output=0x555555726d80) at waybar@exe/xdg-output-unstable-v1-client-protocol.h:175
        id = 0x555555601e68
#2  0x00005555555917d2 in waybar::Bar::Bar(waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> >&&) (this=0x555555601e00, client=..., p_output=...) at ../src/bar.cpp:18
        positionBottom = false
        layerTop = false
        layerSurfaceListener = {configure = 0x555555591c54 <waybar::Bar::_layerSurfaceHandleConfigure(void*, zwlr_layer_surface_v1*, unsigned int, unsigned int, unsigned int)>, closed = 0x555555591e0a <waybar::Bar::_layerSurfaceHandleClosed(void*, zwlr_layer_surface_v1*)>}
        gdkWindow = 0x7fffffffdc50
        xdgOutputListener = 
    {logical_position = 0x555555591bce <waybar::Bar::_handleLogicalPosition(void*, zxdg_output_v1*, int, int)>, logical_size = 0x555555591be4 <waybar::Bar::_handleLogicalSize(void*, zxdg_output_v1*, int, int)>, done = 0x555555591bfa <waybar::Bar::_handleDone(void*, zxdg_output_v1*)>, name = 0x555555591c0a <waybar::Bar::_handleName(void*, zxdg_output_v1*, char const*)>, description = 0x555555591c40 <waybar::Bar::_handleDescription(void*, zxdg_output_v1*, char const*)>}
#3  0x000055555558eca2 in std::make_unique<waybar::Bar, waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> > >(waybar::Client&, std::unique_ptr<wl_output*, std::default_delete<wl_output*> >&&) (__args#0=..., __args#1=...)
    at /usr/include/c++/8.2.0/bits/unique_ptr.h:831
#4  0x000055555558e686 in waybar::Client::_handle_global(void*, wl_registry*, unsigned int, char const*, unsigned int) (data=0x7fffffffe100, registry=0x5555556e1fe0, name=12, interface=0x5555556e22b0 "wl_output", version=2) at ../src/client.cpp:52
        output = std::unique_ptr<wl_output *> = {get() = 0x0}
        o = 0x7fffffffe100
#5  0x00007ffff50fe1c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#6  0x00007ffff50fdc2a in ffi_call () at /usr/lib/libffi.so.6
#7  0x00007ffff7d55f9f in  () at /usr/lib/libwayland-client.so.0
#8  0x00007ffff7d5270a in  () at /usr/lib/libwayland-client.so.0
#9  0x00007ffff7d53c5c in wl_display_dispatch_queue_pending () at /usr/lib/libwayland-client.so.0
#10 0x00007ffff7d540ac in wl_display_roundtrip_queue () at /usr/lib/libwayland-client.so.0
#11 0x000055555558e7e8 in waybar::Client::bind_interfaces() (this=0x7fffffffe100) at ../src/client.cpp:78
        registry_listener = {global = 0x55555558e58a <waybar::Client::_handle_global(void*, wl_registry*, unsigned int, char const*, unsigned int)>, global_remove = 0x55555558e784 <waybar::Client::_handle_global_remove(void*, wl_registry*, unsigned int)>}
#12 0x000055555558e80b in waybar::Client::main(int, char**) (this=0x7fffffffe100, argc=1, argv=0x7fffffffe298) at ../src/client.cpp:83
#13 0x0000555555594647 in main(int, char**) (argc=1, argv=0x7fffffffe298) at ../src/main.cpp:20
        c = 
          {cssFile = "/home/bernardo/.config/waybar/style.css", configFile = "/home/bernardo/.config/waybar/config", gtk_main = <incomplete type>, gdk_display = {pCppObject_ = 0x5555556bea10}, wlDisplay = 0x5555555fa160, registry = 0x5555556e1fe0, layer_shell = 0x555555594831 <_GLOBAL__sub_I_main()+19>, xdg_output_manager = 0x8, seat = 0x555555726e90, bars = std::vector of length 0, capacity 0}
```

## Why:
I got no idea and would love to try to solve this on my own if I knew at least how to do half of this wayland and xdg  wisardry.

## How:
I installed wlroots-git package on AUR and then compiled as told:
```
meson build
ninja -C build
```
meson output:
```
The Meson build system
Version: 0.47.1
Source dir: /home/bernardo/workspace/Waybar
Build dir: /home/bernardo/workspace/Waybar/build
Build type: native build
Project name: waybar
Project version: 0.0.2
Native C compiler: cc (gcc 8.2.0 "cc (GCC) 8.2.0")
Native C++ compiler: c++ (gcc 8.2.0 "c++ (GCC) 8.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Dependency threads found: YES
Found pkg-config: /usr/bin/pkg-config (1.5.3)
Native dependency libinput found: YES 1.11.3
Looking for a fallback subproject for the dependency fmt
Using fmtlib from cache.
Using fmt-4.1.0-1-wrap.zip from cache.

|
|Executing subproject fmtlib 
|
|Project name: fmt
|Project version: 4.1.0
|Native C++ compiler: c++ (gcc 8.2.0 "c++ (GCC) 8.2.0")
|Build targets in project: 1
|
|Subproject fmtlib finished.
Dependency fmt from subproject subprojects/fmtlib found: YES
Native dependency wayland-client found: YES 1.15.0
Native dependency wayland-cursor found: YES 1.15.0
Native dependency wayland-protocols found: YES 1.15
Native dependency wlroots found: YES 0.0.1
Native dependency gtkmm-3.0 found: YES 3.22.2
Native dependency jsoncpp found: YES 1.8.4
Native dependency sigc++-2.0 found: YES 2.10.0
Native dependency libnl-3.0 found: YES 3.4.0
Native dependency libnl-genl-3.0 found: YES 3.4.0
Native dependency libpulse found: YES 12.2
Program wayland-scanner found: YES (/usr/bin/wayland-scanner)
Build targets in project: 3
Found ninja-1.8.2 at /usr/bin/ninja
```

**Comment by Alexays** [comment]
Can you tell me if it's fixed in the last commit ;)

**Comment by tarberd** [comment]
There is no more segmentation fault but the bar does not open.

What should I expect from the waybar command? Am I missing anything? A sway bar configuration? Maybe I need to use the newer wlroots sway and not the 0.15? 

Well, after I can compile and run waybar I can help with documentation I guess.

**Comment by Alexays** [comment]
Ah that's why, yes you must use the wlroots version.
It would be a real pleasure if you'd help me with the documentation :D

**Comment by tarberd** [comment]
Neat! installed through AUR the sway-wlroots-git. Its working, do you think the segmentation fault was due to this as well?

**Comment by Alexays** [comment]
Yes thanks for testing it in this configuration, it was missing a check ;)
