### ISSUE TITLE
Crash in waybar::modules::Custom::update() in case of bad utf-8

### ISSUE THREAD

**Issue by sahib** [Alexays/Waybar#2621]
Hello :wave: 

I noticed periodic crashes when skimming through some YouTube videos, especially those with some unicode codepoints in them. I compiled the latest version of `waybar` to check if it was fixed, but it still happened. I compiled with debug symbols and captured this stack trace in gdb:

```gdb
Thread 1 "waybar" received signal SIGSEGV, Segmentation fault.
0x00007ffff62d594a in wcscoll_l () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff62d594a in wcscoll_l () at /usr/lib/libc.so.6
#1  0x00007ffff6b0e660 in g_utf8_collate () at /usr/lib/libglib-2.0.so.0
#2  0x00005555555ae630 in Glib::operator!=(Glib::ustring const&, Glib::ustring const&) (lhs=..., rhs=...)
    at /usr/include/glibmm-2.4/glibmm/ustring.h:1820
#3  0x00005555555abe23 in waybar::modules::Custom::update() (this=0x555555a817b0) at ../src/modules/custom.cpp:167
#4  0x00005555555e31e3 in operator()() const (__closure=0x555555a16890) at ../src/bar.cpp:783
#5  0x00005555555e4bb4 in sigc::adaptor_functor<waybar::Bar::getModules(const waybar::Factory&, const std::string&,waybar::Group*)::<lambda()> >::operator()(void) const (this=0x555555a16890)
    at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#6  0x00005555555e49b8 in sigc::internal::slot_call0<waybar::Bar::getModules(const waybar::Factory&, const std::string&, waybar::Group*)::<lambda()>, void>::call_it(sigc::internal::slot_rep *) (rep=0x555555a16860)
    at /usr/include/sigc++-2.0/sigc++/functors/slot.h:136
#7  0x00007ffff765375a in Glib::DispatchNotifier::pipe_io_handler(Glib::IOCondition) ()
    at /usr/lib/libglibmm-2.4.so.1
#8  0x00007ffff7653af0 in Glib::IOSource::dispatch(sigc::slot_base*) () at /usr/lib/libglibmm-2.4.so.1
#9  0x00007ffff7654a4f in Glib::Source::dispatch_vfunc(_GSource*, int (*)(void*), void*) ()
    at /usr/lib/libglibmm-2.4.so.1
#10 0x00007ffff6ad2f19 in  () at /usr/lib/libglib-2.0.so.0
#11 0x00007ffff6b312b7 in  () at /usr/lib/libglib-2.0.so.0
#12 0x00007ffff6ad1112 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#13 0x00007ffff6d06af6 in g_application_run () at /usr/lib/libgio-2.0.so.0
#14 0x00005555555faab0 in waybar::Client::main(int, char**) (this=0x555555909ce0, argc=1, argv=0x7fffffffde08)
    at ../src/client.cpp:267
#15 0x00005555555dd26a in main(int, char**) (argc=1, argv=0x7fffffffde08) at ../src/main.cpp:1
```

For context, my config looks like this:

```json

"custom/playerctl": {
	"interval": 1,
	"exec": "~/.config/waybar/modules/playerctl.sh",
	"exec-if": "pgrep playerctl",
	"escape": true,
        "on-click": "playerctl play-pause",
        "on-scroll-up": "playerctl next",
        "on-scroll-down": "playerctl previous"
},
```

The contents of ``playerctl.sh`` read the currently playing track and sometimes cut the resulting string to a fixed byte length, sometimes producing invalid utf-8. For testing purpose I could trigger the issue having a script with this content:

```bash
printf "\xa0\xa1"  # some invalid utf-8
```

I could fix it by validating and skipping invalid utf-8:

```diff
diff --git a/src/modules/custom.cpp b/src/modules/custom.cpp
index 287b5588..491aef43 100644
--- a/src/modules/custom.cpp
+++ b/src/modules/custom.cpp
@@ -155,6 +155,12 @@ auto waybar::modules::Custom::update() -> void {
     } else {
       parseOutputRaw();
     }
+    auto g = Glib::ustring(text_);
+    if(!g.validate()) {
+      return;
+    }

```

That might not be the best fix to be honest, but I first wanted to check what kind of error handling you would prefer:

* Log something and ignore invalid strings. 
* Sanitize the string by leaving out invalid utf8 sequences.
* Still try to display it, but be more careful when using `operator!=`.

Thanks for creating waybar.

**Comment by Alexays** [comment]
Hi!
I'll go for the latest option if possible, or the second.

**Comment by jinnko** [comment]
FWIW - I've been getting core-dumps for a long time and just haven't had the headspace to investigate until last night - when I found this report and it's much better than I would've submitted and seems to match:

Waybar v0.9.22 on Arch

```
Oct 30 16:50:20 teto.ixydo.net systemd-coredump[111657]: [🡕] Process 111528 (waybar) of user 1001 dumped core.
                                                         
                                                         Stack trace of thread 111528:
                                                         #0  0x00007f3f86ad594a __wcscoll_l (libc.so.6 + 0xb794a)
                                                         #1  0x00007f3f873706b0 g_utf8_collate (libglib-2.0.so.0 + 0x956b0)
                                                         #2  0x00005559693faabc n/a (waybar + 0x5fabc)
                                                         #3  0x000055596940f516 n/a (waybar + 0x74516)
                                                         #4  0x00007f3f87ea675a _ZN4Glib16DispatchNotifier15pipe_io_handlerENS_11IOConditionE (>
                                                         #5  0x00007f3f87ea6af0 _ZN4Glib8IOSource8dispatchEPN4sigc9slot_baseE (libglibmm-2.4.so>
                                                         #6  0x00007f3f87ea7a4f _ZN4Glib6Source14dispatch_vfuncEP8_GSourcePFiPvES3_ (libglibmm->
                                                         #7  0x00007f3f87334f69 n/a (libglib-2.0.so.0 + 0x59f69)
                                                         #8  0x00007f3f87393327 n/a (libglib-2.0.so.0 + 0xb8327)
                                                         #9  0x00007f3f87333162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
                                                         #10 0x00007f3f87506b16 g_application_run (libgio-2.0.so.0 + 0xdfb16)
                                                         #11 0x00005559693e8887 n/a (waybar + 0x4d887)
                                                         #12 0x00005559693e65b5 main (waybar + 0x4b5b5)
                                                         #13 0x00007f3f86a45cd0 n/a (libc.so.6 + 0x27cd0)
                                                         #14 0x00007f3f86a45d8a __libc_start_main (libc.so.6 + 0x27d8a)
                                                         #15 0x00005559693ed755 n/a (waybar + 0x52755)
                                                         
                                                         Stack trace of thread 111530:
                                                         #0  0x00007f3f86b2c73d syscall (libc.so.6 + 0x10e73d)
                                                         #1  0x00007f3f8738e2b7 g_cond_wait (libglib-2.0.so.0 + 0xb32b7)
                                                         #2  0x00007f3f873001b4 n/a (libglib-2.0.so.0 + 0x251b4)
                                                         #3  0x00007f3f87368a7e n/a (libglib-2.0.so.0 + 0x8da7e)
                                                         #4  0x00007f3f873669f5 n/a (libglib-2.0.so.0 + 0x8b9f5)
                                                         #5  0x00007f3f86aaa9eb n/a (libc.so.6 + 0x8c9eb)
                                                         #6  0x00007f3f86b2e7cc n/a (libc.so.6 + 0x1107cc)
...truncated the rest...
```

**Comment by sahib** [comment]
I now added a PR in #2624 for this issue. It implements the third option, more or less. It looks like this in case of invalid UTF-8:

![image](https://github.com/Alexays/Waybar/assets/376651/5d153830-aae5-4f8b-86ef-23ca0caad243)

Closing this issue, please move discussion to the PR.
