### ISSUE TITLE
Waybar crashes repeatedly in the same way at random times in wcscoll_l()

### ISSUE THREAD

**Issue by fmgh001** [Alexays/Waybar#2829]
Here is the stack trace

Thread 1 "waybar" received signal SIGSEGV, Segmentation fault.
0x00007ffff61fe3ea in wcscoll_l () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff61fe3ea in wcscoll_l () at /lib64/libc.so.6
#1  0x00007ffff68f3d0f in g_utf8_collate () at /usr/lib64/libglib-2.0.so.0
#2  0x00005555555e899f in Glib::operator!=(Glib::ustring const&, Glib::ustring const&) (rhs=..., lhs=...) at /usr/include/glibmm-2.4/glibmm/ustring.h:1820
#3  waybar::modules::Custom::update() (this=0x555555904580) at ../Waybar-0.9.24/src/modules/custom.cpp:172
#4  0x000055555560e829 in operator() (__closure=<optimized out>) at ../Waybar-0.9.24/src/bar.cpp:783
#5  sigc::adaptor_functor<waybar::Bar::getModules(const waybar::Factory&, const std::string&, waybar::Group*)::<lambda()> >::operator() (this=<optimized out>) at /usr/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#6  sigc::internal::slot_call0<waybar::Bar::getModules(const waybar::Factory&, const std::string&, waybar::Group*)::<lambda()>, void>::call_it(sigc::internal::slot_rep *) (rep=0x555555a385a0) at /usr/include/sigc++-2.0/sigc++/functors/slot.h:136
#7  0x00007ffff76d238a in sigc::internal::signal_emit0<void, sigc::nil>::emit(sigc::internal::signal_impl*) () at /usr/lib64/libglibmm-2.4.so.1
#8  0x00007ffff76d1c39 in Glib::DispatchNotifier::pipe_io_handler(Glib::IOCondition) () at /usr/lib64/libglibmm-2.4.so.1
#9  0x00007ffff76d4480 in Glib::IOSource::dispatch(sigc::slot_base*) () at /usr/lib64/libglibmm-2.4.so.1
#10 0x00007ffff76d3fb7 in Glib::Source::dispatch_vfunc(_GSource*, int (*)(void*), void*) () at /usr/lib64/libglibmm-2.4.so.1
#11 0x00007ffff68b5888 in  () at /usr/lib64/libglib-2.0.so.0
#12 0x00007ffff68b8c97 in  () at /usr/lib64/libglib-2.0.so.0
#13 0x00007ffff68b92e0 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#14 0x00007ffff6af5ecd in g_application_run () at /usr/lib64/libgio-2.0.so.0
#15 0x00005555555af1fc in waybar::Client::main(int, char**) (this=this@entry=0x5555557efd00, argc=<optimized out>, argc@entry=1, argv=<optimized out>, argv@entry=0x7fffffffdef8) at /usr/include/glibmm-2.4/glibmm/refptr.h:259
#16 0x00005555555ad7d5 in main(int, char**) (argc=1, argv=0x7fffffffdef8) at ../Waybar-0.9.24/src/main.cpp:106

(gdb) i r
rax            0x5555557fa7b0      93824995010480
rbx            0x0                 0
rcx            0xffffffb0          4294967216
rdx            0x42                66
rsi            0x0                 0
rdi            0x5555559e80b0      93824997032112
rbp            0x5555559e80b0      0x5555559e80b0
rsp            0x7fffffffcda0      0x7fffffffcda0
r8             0x72                114
r9             0x0                 0
r10            0x1                 1
r11            0x68                104
r12            0x7fffffffcf50      140737488342864
r13            0x555555904780      93824996099968
r14            0x555555904668      93824996099688
r15            0x5555558ae6f0      93824995747568
rip            0x7ffff61fe3ea      0x7ffff61fe3ea <wcscoll_l+58>
eflags         0x10202             [ IF RF ]
cs             0x33                51
ss             0x2b                43
ds             0x0                 0
es             0x0                 0
fs             0x0                 0
gs             0x0                 0
k0             0x0                 0
k1             0x0                 0
k2             0x0                 0
k3             0x0                 0
k4             0x0                 0
k5             0x0                 0
k6             0x0                 0
k7             0x0                 0

=> 0x7ffff61fe3ea <wcscoll_l+58>:       mov    ecx,DWORD PTR [rbx]
   0x7ffff61fe3ec <wcscoll_l+60>:       test   edx,edx
   0x7ffff61fe3ee <wcscoll_l+62>:       je     0x7ffff61ff22a <wcscoll_l+3706>
   0x7ffff61fe3f4 <wcscoll_l+68>:       test   ecx,ecx
   0x7ffff61fe3f6 <wcscoll_l+70>:       je     0x7ffff61ff22a <wcscoll_l+3706>
   0x7ffff61fe3fc <wcscoll_l+76>:       mov    rbx,QWORD PTR [rax+0x40]
   0x7ffff61fe400 <wcscoll_l+80>:       mov    r15,QWORD PTR [rax+0x80]
   0x7ffff61fe407 <wcscoll_l+87>:       mov    r8,QWORD PTR [rax+0x88]
   0x7ffff61fe40e <wcscoll_l+94>:       mov    QWORD PTR [rsp+0x18],rbx
   0x7ffff61fe413 <wcscoll_l+99>:       mov    rbx,QWORD PTR [rax+0x90]
   0x7ffff61fe41a <wcscoll_l+106>:      mov    rax,QWORD PTR [rax+0x98]
   0x7ffff61fe421 <wcscoll_l+113>:      mov    QWORD PTR [rsp+0x20],rbx
   0x7ffff61fe426 <wcscoll_l+118>:      mov    QWORD PTR [rsp+0x8],rax
   0x7ffff61fe42b <wcscoll_l+123>:      test   r15b,0x3
   0x7ffff61fe42f <wcscoll_l+127>:      jne    0x7ffff61ff2a1 <wcscoll_l+3825>
   0x7ffff61fe435 <wcscoll_l+133>:      test   r8b,0x3

Looks like a null deref. If you need more details let me know.

**Comment by fmgh001** [comment]
Would love to learn more on why this is happening. I can provide more traces or inspection. This bug is very frequent.
