### ISSUE TITLE
waybar crashes after suspend

### ISSUE THREAD

**Issue by 1player** [Alexays/Waybar#3315]
```
                                                     Stack trace of thread 7029:
                                                     #0  0x00007f4d016ab144 __pthread_kill_implementation (libc.so.6 + 0x98144)
                                                     #1  0x00007f4d0165365e raise (libc.so.6 + 0x4065e)
                                                     #2  0x00007f4d0163b902 abort (libc.so.6 + 0x28902)
                                                     #3  0x00007f4d018a5d99 _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold (libstdc++.so.6 + 0xa5d99)
                                                     #4  0x00007f4d018b7b7c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb7b7c)
                                                     #5  0x00007f4d018a5941 _ZSt9terminatev (libstdc++.so.6 + 0xa5941)
                                                     #6  0x00007f4d018b7e08 __cxa_throw (libstdc++.so.6 + 0xb7e08)
                                                     #7  0x000056104b693854 _ZN6waybar4util10JsonParser5parseERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold (waybar + 0x2d854)
                                                     #8  0x000056104b754209 _ZN6waybar7modules8hyprland3IPC19getSocket1JsonReplyERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (waybar + 0xee209)
                                                     #9  0x000056104b76751b .LTHUNK0.lto_priv.4 (waybar + 0x10151b)
                                                     #10 0x000056104b752f7a _ZZN6waybar7modules8hyprland3IPC8startIPCEvENKUlvE_clEv (waybar + 0xecf7a)
                                                     #11 0x00007f4d018e6524 execute_native_thread_routine (libstdc++.so.6 + 0xe6524)
                                                     #12 0x00007f4d016a91b7 start_thread (libc.so.6 + 0x961b7)
                                                     #13 0x00007f4d0172b39c __clone3 (libc.so.6 + 0x11839c)
```

Module waybar from rpm waybar-0.10.3-1.fc40.x86_64

Core dump attached. [core.waybar.1000.45b174385d5a4fb68ad945b6777797be.6819.1717158559000000.gz](https://github.com/user-attachments/files/15513687/core.waybar.1000.45b174385d5a4fb68ad945b6777797be.6819.1717158559000000.gz)

**Comment by LennertVA** [comment]
Can confirm that waybar still doesn't survive a suspend/resume. Backtrace is not very useful on my side:

```
Core was generated by `/usr/bin/waybar'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f0e620a7a2c in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f0e127fc6c0 (LWP 1792))]
(gdb) bt full
#0  0x00007f0e620a7a2c in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007f0e6204d1a0 in raise () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007f0e620345fe in abort () from /usr/lib/libc.so.6
No symbol table info available.
#3  0x00007f0e62297bf6 in ?? () from /usr/lib/libstdc++.so.6
No symbol table info available.
#4  0x00007f0e622b1eba in ?? () from /usr/lib/libstdc++.so.6
No symbol table info available.
#5  0x00007f0e622975d9 in std::terminate() () from /usr/lib/libstdc++.so.6
No symbol table info available.
#6  0x00007f0e622b2176 in __cxa_throw () from /usr/lib/libstdc++.so.6
No symbol table info available.
#7  0x00005568a7ff396e in ?? ()
No symbol table info available.
#8  0x00005568a80958e2 in ?? ()
No symbol table info available.
#9  0x00005568a80533d6 in ?? ()
No symbol table info available.
#10 0x00007f0e622e55a4 in ?? () from /usr/lib/libstdc++.so.6
No symbol table info available.
#11 0x00007f0e620a597a in ?? () from /usr/lib/libc.so.6
No symbol table info available.
#12 0x00007f0e621292bc in ?? () from /usr/lib/libc.so.6
No symbol table info available.
```

**Comment by Alexays** [comment]
Closing — this crash is already fixed on current master and will be in the next release. Please reopen if it still reproduces on a git build. 🙏

(Hyprland IPC empty-reply guard + try/catch (same fix as #3012))
