### ISSUE TITLE
ModuleNotFoundError: No module named 'packaging'

### ISSUE THREAD

**Issue by fluffiflower** [Alexays/Waybar#3319]
Hi, i tried installing waybar-cava on arch.
i get this error:

Found ninja-1.12.1 at /usr/bin/ninja
ninja: Entering directory `build'                                                                      
[19/177] Generating protocol/dbus-status-notifier-watcher.[ch] with a custom command
FAILED: protocol/dbus-status-notifier-watcher.c protocol/dbus-status-notifier-watcher.h 
/usr/bin/gdbus-codegen --c-namespace Sn --generate-c-code protocol/dbus-status-notifier-watcher ../protocol/./dbus-status-notifier-watcher.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[21/177] Generating protocol/dbus-status-notifier-item.[ch] with a custom command
FAILED: protocol/dbus-status-notifier-item.c protocol/dbus-status-notifier-item.h 
/usr/bin/gdbus-codegen --c-namespace Sn --generate-c-code protocol/dbus-status-notifier-item ../protocol/./dbus-status-notifier-item.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[22/177] Generating protocol/dbus-menu.[ch] with a custom command
FAILED: protocol/dbus-menu.c protocol/dbus-menu.h 
/usr/bin/gdbus-codegen --c-namespace Sn --generate-c-code protocol/dbus-menu ../protocol/./dbus-menu.xml
Traceback (most recent call last):
  File "/usr/bin/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/usr/share/glib-2.0/codegen/codegen_main.py", line 30, in <module>
    from . import dbustypes
  File "/usr/share/glib-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/usr/share/glib-2.0/codegen/utils.py", line 22, in <module>
    import packaging.version
ModuleNotFoundError: No module named 'packaging'
[28/177] Generating 'waybar.p/river-control-unstable-v1-client-protocol.h'
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: waybar-cava-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
waybar-cava - exit status 4

Does anyone know how to fix it?

**Comment by zjeffer** [comment]
`sudo pacman -S python-packaging`
