### ISSUE TITLE
mediaplayer script does not work on NixOS

### ISSUE THREAD

**Issue by notquitethereyet** [Alexays/Waybar#3776]
I am pretty new to NixOS so please bear with me. 
```
❯ mediaplayer.py
Traceback (most recent call last):
  File "/home/quiet/.config/hypr/scripts/mediaplayer.py", line 3, in <module>
    gi.require_version("Playerctl", "2.0")
  File "/nix/store/ga0gzj1910mpidn24rc13f1ih2gmj3gd-python3.12-pygobject-3.50.0/lib/python3.12/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Playerctl not available
```
I am importing my packages.nix which has the system packages and the python.nix which has the python packages.
this is my python.nix
```
{ pkgs }:

let
  pythonEnv = pkgs.python312.withPackages (pythonPackages: with pythonPackages; [
    numpy
    pandas
    matplotlib
    requests
    pygobject3
    # Add more Python packages here
  ]);
in
{
  pythonEnv = pythonEnv;
}

```
Any help with this?

**Comment by benjamb** [comment]
@notquitethereyet Are you sure you want to use the mediaplayer script rather than the `mpris` module?

**Comment by notquitethereyet** [comment]
@benjamb hey thank for your reply. I have the same config on arch linux so i never looked at an alternative. can you point me in the right direction of how to use the mpris module for the music player module on waybar?

**Comment by notquitethereyet** [comment]
edit: worked with waybar-mpris

**Comment by fueguchi** [comment]
with this flake you can import playerctl from gi, if you prefer mediaplayer.py instead of waybar-mpris
```nix
{
  description = "import glib and playerctl from gi";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  };

  outputs = { self, nixpkgs }: 
  let
    system = "x86_64-linux";

    pkgs = import nixpkgs { inherit system; };
    python = (pkgs.python312.withPackages (pythonPackages: with pythonPackages; [ 
      pygobject3
    ]));

  in
   {
    devShells.${system}.default = pkgs.mkShell {
      propagatedBuildInputs =  [
        python
        pkgs.gobject-introspection
        pkgs.playerctl
      ];
    };
  };
}
```
```sh
python
Python 3.12.8 (main, Dec  3 2024, 18:42:41) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> gi.require_version("Playerctl", "2.0")
>>> 
```
