### ISSUE TITLE
Core Dump on Fedora30

### ISSUE THREAD

**Issue by nielsk** [Alexays/Waybar#378]
After compiling strace and starting it, it core dumps. I attached an strace.
[waybar_strace.txt](https://github.com/Alexays/Waybar/files/3274775/waybar_strace.txt)

**Comment by Alexays** [comment]
Can you get gdb backtrace?

**Comment by nielsk** [comment]
I hope this is the right thing to do:
```
(gdb) run
Starting program: /usr/bin/waybar 
Missing separate debuginfos, use: dnf debuginfo-install waybar-0.6.8-1.fc30.x86_64
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe835b700 (LWP 2358)]
[New Thread 0x7fffe7b5a700 (LWP 2359)]
[New Thread 0x7fffe729f700 (LWP 2362)]
[New Thread 0x7fffe6a9e700 (LWP 2363)]
[2019-06-11 10:55:47.158] [info] Resources files: /etc/xdg/waybar/config, /etc/xdg/waybar/style.css

Thread 1 "waybar" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f8071a in wl_proxy_marshal_constructor () from /lib64/libwayland-client.so.0
(gdb) backtrace
#0  0x00007ffff7f8071a in wl_proxy_marshal_constructor () at /lib64/libwayland-client.so.0
#1  0x00005555555b55f7 in waybar::Client::handleOutput(std::unique_ptr<waybar::waybar_output, std::default_delete<waybar::waybar_output> >&) ()
#2  0x00005555555b5fa1 in waybar::Client::handleGlobal(void*, wl_registry*, unsigned int, char const*, unsigned int) ()
#3  0x00007ffff64d3b28 in ffi_call_unix64 () at /lib64/libffi.so.6
#4  0x00007ffff64d3339 in ffi_call () at /lib64/libffi.so.6
#5  0x00007ffff7f83607 in  () at /lib64/libwayland-client.so.0
#6  0x00007ffff7f7ff18 in  () at /lib64/libwayland-client.so.0
#7  0x00007ffff7f8146c in wl_display_dispatch_queue_pending () at /lib64/libwayland-client.so.0
#8  0x00007ffff7f818ab in wl_display_roundtrip_queue () at /lib64/libwayland-client.so.0
#9  0x00005555555b5a83 in waybar::Client::bindInterfaces() ()
#10 0x000055555558149c in waybar::Client::main(int, char**) ()
#11 0x0000555555580474 in main ()
```

**Comment by Alexays** [comment]
Whats your sway/wlroots version?

**Comment by nielsk** [comment]
I am using sway from a 3rd-party-copr-repo (it didn't work with the official either) and tried to use waybar from there as well (also core dump)
sway: 1.1.1-1
wlroots: 0.6.0

The versions from the official repo are far behind
sway: 0.15.2
wlroots: 0.1

**Comment by Alexays** [comment]
Is the problem still present?

**Comment by nielsk** [comment]
Sorry for not closing it. It works now.

**Comment by nielsk** [comment]
and I didn't do anything as far as I know.
