### ISSUE TITLE
SIGABRT on Gentoo

### ISSUE THREAD

**Issue by lovesegfault** [Alexays/Waybar#422]
Info: 
```
coredumpctl gdb 1938
           PID: 1938 (waybar)
           UID: 1000 (bemeurer)
           GID: 1000 (bemeurer)
        Signal: 6 (ABRT)
     Timestamp: Thu 2019-08-01 15:09:01 PDT (1min 27s ago)
  Command Line: /home/bemeurer/bin/waybar -b bar-0
    Executable: /home/bemeurer/src/Waybar/build/waybar
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (bemeurer)
       Boot ID: 346f60a970714ed396f15052601ba4bc
    Machine ID: e6802cc2780aff60e24518245c4f1980
      Hostname: bergman
       Storage: /var/lib/systemd/coredump/core.waybar.1000.346f60a970714ed396f15052601ba4bc.1938.1564697341000000000000.lz4
       Message: Process 1938 (waybar) of user 1000 dumped core.
```

```
#0  0x00007fb05c18fcc1 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fb05c179535 in __GI_abort () at abort.c:79
#2  0x00007fb05c1d59f7 in __libc_message (action=<optimized out>, fmt=fmt@entry=0x7fb05c2ec8bc "*** %s ***: %s terminated\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fb05c26f8c5 in __GI___fortify_fail_abort (need_backtrace=need_backtrace@entry=false, msg=msg@entry=0x7fb05c2ec89a "stack smashing detected") at fortify_fail.c:28
#4  0x00007fb05c26f862 in __stack_chk_fail () at stack_chk_fail.c:29
#5  0x00007fb05cdf5c3d in  () at /usr/lib64/libgtk-3.so.0
#6  0x00007fb05d0a4b67 in gtk_container_propagate_draw () at /usr/lib64/libgtk-3.so.0
#7  0x00007fb05d0a4c6c in  () at /usr/lib64/libgtk-3.so.0
#8  0x00007fb05d0ea8fd in  () at /usr/lib64/libgtk-3.so.0
#9  0x00007fb05d093f1d in  () at /usr/lib64/libgtk-3.so.0
#10 0x00007fb05d09c3cb in  () at /usr/lib64/libgtk-3.so.0
#11 0x00007fb05d0e7cd1 in  () at /usr/lib64/libgtk-3.so.0
#12 0x00007fb05d9ecca0 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /usr/lib64/libgtkmm-3.0.so.1
#13 0x00007fb05cdf5904 in  () at /usr/lib64/libgtk-3.so.0
#14 0x00007fb05d0a4b67 in gtk_container_propagate_draw () at /usr/lib64/libgtk-3.so.0
#15 0x00007fb05d0a4c6c in  () at /usr/lib64/libgtk-3.so.0
#16 0x00007fb05d0f933d in  () at /usr/lib64/libgtk-3.so.0
#17 0x00007fb05d093f1d in  () at /usr/lib64/libgtk-3.so.0
#18 0x00007fb05d09c3cb in  () at /usr/lib64/libgtk-3.so.0
#19 0x00007fb05d0f9b91 in  () at /usr/lib64/libgtk-3.so.0
#20 0x00007fb05d9ecca0 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /usr/lib64/libgtkmm-3.0.so.1
#21 0x00007fb05cdf5904 in  () at /usr/lib64/libgtk-3.so.0
#22 0x00007fb05d0a4b67 in gtk_container_propagate_draw () at /usr/lib64/libgtk-3.so.0
#23 0x00007fb05d0a4c6c in  () at /usr/lib64/libgtk-3.so.0
#24 0x00007fb05d037e4c in  () at /usr/lib64/libgtk-3.so.0
#25 0x00007fb05d9ecca0 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /usr/lib64/libgtkmm-3.0.so.1
#26 0x00007fb05cdf5904 in  () at /usr/lib64/libgtk-3.so.0
#27 0x00007fb05d0a4b67 in gtk_container_propagate_draw () at /usr/lib64/libgtk-3.so.0
#28 0x00007fb05d0a4c6c in  () at /usr/lib64/libgtk-3.so.0
#29 0x00007fb05d0f933d in  () at /usr/lib64/libgtk-3.so.0
#30 0x00007fb05d093f1d in  () at /usr/lib64/libgtk-3.so.0
#31 0x00007fb05d09c3cb in  () at /usr/lib64/libgtk-3.so.0
#32 0x00007fb05d0f9b91 in  () at /usr/lib64/libgtk-3.so.0
#33 0x00007fb05d9ecca0 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /usr/lib64/libgtkmm-3.0.so.1
#34 0x00007fb05cdf5904 in  () at /usr/lib64/libgtk-3.so.0
#35 0x00007fb05d0a4b67 in gtk_container_propagate_draw () at /usr/lib64/libgtk-3.so.0
#36 0x00007fb05d0a4c6c in  () at /usr/lib64/libgtk-3.so.0
#37 0x00007fb05d0f933d in  () at /usr/lib64/libgtk-3.so.0
#38 0x00007fb05d093f1d in  () at /usr/lib64/libgtk-3.so.0
#39 0x00007fb05d09c3cb in  () at /usr/lib64/libgtk-3.so.0
#40 0x00007fb05d0f9b91 in  () at /usr/lib64/libgtk-3.so.0
#41 0x00007fb05d9ecca0 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /usr/lib64/libgtkmm-3.0.so.1
#42 0x00007fb05cdf5904 in  () at /usr/lib64/libgtk-3.so.0
#43 0x00007fb05d0a4b67 in gtk_container_propagate_draw () at /usr/lib64/libgtk-3.so.0
#44 0x00007fb05d0a4c6c in  () at /usr/lib64/libgtk-3.so.0
#45 0x00007fb05cdc392d in  () at /usr/lib64/libgtk-3.so.0
#46 0x00007fb05d9ecca0 in Gtk::Widget_Class::draw_callback(_GtkWidget*, _cairo*) () at /usr/lib64/libgtkmm-3.0.so.1
#47 0x00007fb05cdf5904 in  () at /usr/lib64/libgtk-3.so.0
#48 0x00007fb05cddc71c in  () at /usr/lib64/libgtk-3.so.0
#49 0x00007fb05cf960f9 in gtk_main_do_event () at /usr/lib64/libgtk-3.so.0
#50 0x00007fb05cc87460 in  () at /usr/lib64/libgdk-3.so.0
#51 0x00007fb05cc74a13 in  () at /usr/lib64/libgdk-3.so.0
#52 0x00007fb05cc76af5 in  () at /usr/lib64/libgdk-3.so.0
#53 0x00007fb05cc76d18 in  () at /usr/lib64/libgdk-3.so.0
#54 0x00007fb05c99d9ab in g_signal_emit_valist () at /usr/lib64/libgobject-2.0.so.0
#55 0x00007fb05c98c497 in g_signal_emit () at /usr/lib64/libgobject-2.0.so.0
#56 0x00007fb05cc825af in  () at /usr/lib64/libgdk-3.so.0
#57 0x00007fb05cc8f372 in  () at /usr/lib64/libgdk-3.so.0
#58 0x00007fb05c89a1fc in  () at /usr/lib64/libglib-2.0.so.0
#59 0x00007fb05c8a1d19 in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#60 0x00007fb05c8a29cb in  () at /usr/lib64/libglib-2.0.so.0
#61 0x00007fb05c8a6549 in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#62 0x00007fb05caa702d in g_application_run () at /usr/lib64/libgio-2.0.so.0
#63 0x0000556ee4e2870f in waybar::Client::main(int, char**) ()
#64 0x0000556ee4e277d4 in main ()
```

**Comment by Alexays** [comment]
You still have the error?
I'll reopen if yes
