### ISSUE TITLE
Segmentation Fault with enabled pulseaudio module

### ISSUE THREAD

**Issue by eternal-sorrow** [Alexays/Waybar#64]
When I run waybar with enabled pulseaudio module, I get instant segfault.
I rebuilt waybar with debug symbols, ran it with gdb and got this traceback:
```
#0  0x000055555559f1a2 in waybar::modules::Pulseaudio::sinkInfoCb (i=0x7fffe27fb680, data=0x5555556f2290) at ../waybar-9999/src/modules/pulseaudio.cpp:92
#1  0x00007ffff6d42efb in ?? () from /usr/lib64/libpulse.so.0
#2  0x00007ffff4ad8c11 in ?? () from /usr/lib64/pulseaudio/libpulsecommon-12.2.so
#3  0x00007ffff4ad8f63 in pa_pdispatch_run () from /usr/lib64/pulseaudio/libpulsecommon-12.2.so
#4  0x00007ffff6d3847e in ?? () from /usr/lib64/libpulse.so.0
#5  0x00007ffff4adb9cf in ?? () from /usr/lib64/pulseaudio/libpulsecommon-12.2.so
#6  0x00007ffff4ade44b in ?? () from /usr/lib64/pulseaudio/libpulsecommon-12.2.so
#7  0x00007ffff4ade7e9 in ?? () from /usr/lib64/pulseaudio/libpulsecommon-12.2.so
#8  0x00007ffff4adf04f in ?? () from /usr/lib64/pulseaudio/libpulsecommon-12.2.so
#9  0x00007ffff6d4c360 in pa_mainloop_dispatch () from /usr/lib64/libpulse.so.0
#10 0x00007ffff6d4c72e in pa_mainloop_iterate () from /usr/lib64/libpulse.so.0
#11 0x00007ffff6d4c7b0 in pa_mainloop_run () from /usr/lib64/libpulse.so.0
#12 0x00007ffff6d5a096 in ?? () from /usr/lib64/libpulse.so.0
#13 0x00007ffff4aee7a8 in ?? () from /usr/lib64/pulseaudio/libpulsecommon-12.2.so
#14 0x00007ffff655396a in start_thread () from /lib64/libpthread.so.0
#15 0x00007ffff6287d3f in clone () from /lib64/libc.so.6
```

**Comment by eternal-sorrow** [comment]
Okay, just compiled from master. Seems working. Thanks!
