### ISSUE TITLE
[mopidy/mpd] abort (core dumped)

### ISSUE THREAD

**Issue by sseneca** [Alexays/Waybar#775]
I'm having an issue that looks similar to #464. When I use mopidy/mpd, `waybar` crashes, with errors that look like this:

```
[2020-07-17 22:56:08.565] [error] mpd: @՛eAV
waybar: ../src/status.c:334: mpd_status_get_consume: Assertion `status != NULL' failed.
zsh: abort (core dumped)  waybar
```

I compiled Waybar from source, here is the stack trace:

```
Core was generated by `./build/waybar'.
Program terminated with signal SIGABRT, Aborted.

warning: Unexpected size of section `.reg-xstate/73336' in core file.
#0  0x00007f312c050355 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f312afaee40 (LWP 73336))]
(gdb) bt full
#0  0x00007f312c050355 in raise () at /usr/lib/libc.so.6
#1  0x00007f312c039853 in abort () at /usr/lib/libc.so.6
#2  0x00007f312c039727 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007f312c048936 in  () at /usr/lib/libc.so.6
#4  0x00007f312c56e39b in  () at /usr/lib/libmpdclient.so.2
#5  0x0000556b3c0a77a8 in waybar::modules::MPD::setLabel() ()
#6  0x0000556b3c0a9610 in waybar::modules::MPD::update() ()
#7  0x0000556b3c0591f7 in sigc::internal::slot_call0<waybar::Bar::getModules(waybar::Factory const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}, void>::call_it(sigc::internal::slot_rep*) ()
#8  0x00007f312d27141a in Glib::DispatchNotifier::pipe_io_handler(Glib::IOCondition) () at /usr/lib/libglibmm-2.4.so.1
#9  0x00007f312d26e27c in Glib::IOSource::dispatch(sigc::slot_base*) () at /usr/lib/libglibmm-2.4.so.1
#10 0x00007f312d270b67 in Glib::Source::dispatch_vfunc(_GSource*, int (*)(void*), void*) () at /usr/lib/libglibmm-2.4.so.1
#11 0x00007f312c699340 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x00007f312c6e71d9 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007f312c698221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x00007f312c894c9e in g_application_run () at /usr/lib/libgio-2.0.so.0
#15 0x0000556b3c02a88f in waybar::Client::main(int, char**) ()
#16 0x0000556b3c0299dc in main ()
```

If I should close this issue and leave this as a comment on the other issue then let me know. Thanks!

**Comment by Alexays** [comment]
Should not crash anymore with 759602af64e10948af9665813af05237e36ad845

**Comment by sseneca** [comment]
unfortunately that did not fix it for me :thinking: are there any other logs I can send that will be helpful?

```
Core was generated by `./build/waybar'.
Program terminated with signal SIGABRT, Aborted.

warning: Unexpected size of section `.reg-xstate/93249' in core file.
#0  0x00007f35bd94a355 in raise () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f35bc8a8e40 (LWP 93249))]
(gdb) bt full
#0  0x00007f35bd94a355 in raise () at /usr/lib/libc.so.6
#1  0x00007f35bd933853 in abort () at /usr/lib/libc.so.6
#2  0x00007f35bd933727 in _nl_load_domain.cold () at /usr/lib/libc.so.6
#3  0x00007f35bd942936 in  () at /usr/lib/libc.so.6
#4  0x00007f35bde6839b in  () at /usr/lib/libmpdclient.so.2
#5  0x0000557cea97a7de in waybar::modules::MPD::setLabel() ()
#6  0x0000557cea97c650 in waybar::modules::MPD::update() ()
#7  0x0000557cea92c207 in sigc::internal::slot_call0<waybar::Bar::getModules(waybar::Factory const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)::{lambda()#1}, void>::call_it(sigc::internal::slot_rep*) ()
#8  0x00007f35beb6b41a in Glib::DispatchNotifier::pipe_io_handler(Glib::IOCondition) () at /usr/lib/libglibmm-2.4.so.1
#9  0x00007f35beb6827c in Glib::IOSource::dispatch(sigc::slot_base*) () at /usr/lib/libglibmm-2.4.so.1
#10 0x00007f35beb6ab67 in Glib::Source::dispatch_vfunc(_GSource*, int (*)(void*), void*) () at /usr/lib/libglibmm-2.4.so.1
#11 0x00007f35bdf93340 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#12 0x00007f35bdfe11d9 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007f35bdf92221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x00007f35be18ec9e in g_application_run () at /usr/lib/libgio-2.0.so.0
#15 0x0000557cea8fd89f in waybar::Client::main(int, char**) ()
#16 0x0000557cea8fc9ec in main ()
```

**Comment by jbenden** [comment]
Would you mind trying latest master branch, with #887 included?

Thanks,
-Joe

**Comment by dvzrv** [comment]
Hi! I've experienced the same issue (with 0.9.4) on Arch Linux.

After rebuilding the package with #887 applied, I don't get the crash anymore (which usually happened after idle and then unlocking the screen again).
